* About this repository                                            :noexport:
  We currently have an [[https://gitlab.phaidra.org/phaidra-dev/phaidra-demo][automated installer for phaidra]], which allows to set up an instance in about 15min.  However, setup is still bound to the underlying operating system (Ubuntu 22.04-LTS), which brings quite some complexity to the end-user.  Here we try to abstract the system further and allow for easier integration into CI/CD workflows using containerization via docker, and to achieve better portability to other platforms supporting this kind of containerization.

  The end-goal of this project is to allow an interested person to run the command ~docker compose up~ from a clone of this repo and have phaidra running on his/her computer, without modifying the computer (and have things easily removed with ~docker compose down~ as well).

* Table of Contents                                               :TOC:
- [[#technical-sketch][Technical sketch]]
- [[#changes-to-the-phaidra-api-repo][changes to the phaidra-api repo]]
- [[#changes-on-the-toplevel][changes on the toplevel]]

* Technical sketch
  This is work in progress.
  #+NAME: technical-sketch
  #+begin_src dot :file "./images/construction.svg" :exports results
    graph G {
        graph [rankdir="TB"]
        subgraph cluster_host {
            label = "host";
            color = red;
            node [shape = component, style = solid, color = red]
            a1 [label="webserver"];
            subgraph cluster_host_storage {
                label = "host filesystem";
                node [shape = folder, style = solid, color = blue]
                color = blue;
                b1 [label="fedora storage"];
                b2 [label="mariadb storage"];
                b3 [label="mongodb storage"];
                b4 [label="imageserver storage"];
                b5 [label="solr storage"];
                b6 [label="ldap storage"];
            }
            subgraph cluster_docker_network_host {
                label="docker network";
                node [shape = component, style = solid, color = green]
                color = green;
                c1 [label="fedora (data and metadata store)"];
                c2 [label="phaidra-api (general transmitter)"];
                c3 [label="mariadb (general databases)"];
                c4 [label="mongodb (databases for job-tracking)"];
                c5 [label="phaidra-ui (user webinterface)"];
                c6 [label="ldap"];
                c7 [label="solr (site search engine)"];
                c8 [label="imageserver (display large images)"];
                c9 [label="pixelgecko (imageserver fileformat conversion)"]
            }}

        d1 [label="Phaidra User", shape = tripleoctagon, style = solid]

            c1 -- c2 [color="green"];
            c2 -- c3 [color="green"];
            c2 -- c4 [color="green"];
            c2 -- c5 [color="green"];
            c2 -- c6 [color="green"];
            c7 -- c5 [color="green"];
            c5 -- c1 [color="green"];
            c1 -- c3 [color="green"];
            c2 -- c8 [color="green"];
            c2 -- c7 [color="green"];
            c9 -- c8 [color="green"];
            c9 -- c4 [color="green"];

            b1 -- c1 [color="blue"];
            b2 -- c3 [color="blue"];
            b3 -- c4 [color="blue"];
            b4 -- c8 [color="blue"];
            b5 -- c7 [color="blue"];
            b6 -- c6 [color="blue"];

            a1 -- d1 [color="red"];
            c2 -- a1 [color="red"];
            c5 -- a1 [color="red"];

    }
  #+end_src

  #+RESULTS: technical-sketch
  [[file:./images/construction.svg]]

* changes to the phaidra-api repo
  + removed symlinks
  + copied PhaidraAPI.json.example to PhaidraAPI.json
  + run untabify on PhaidraAPI.json
  + run whitespace-cleanup-region on wholly marked buffer
  + removed colon in line 94
  + added colon in line 202
  + copied log4perl.conf from sandbox02
  + changed directory_class from ~Phaidra::Directory::Univie~ to ~Phaidra::Directory::GenericLDAP~.
* changes on the toplevel
  + create [[file:./phaidra.yml][phaidra.yml stub]]
