#+OPTIONS: toc:nil ^:nil
* About this repository
  We currently have an [[https://gitlab.phaidra.org/phaidra-dev/phaidra-demo][automated installer for phaidra]], which allows to set up an instance in about 15min.  However, setup is still bound to the underlying operating system (Ubuntu 22.04-LTS), which brings quite some complexity to the end-user.  Here we try to abstract the system further and allow for easier integration into CI/CD workflows using containerization via docker, and to achieve better portability to other platforms supporting this kind of containerization.

  The goal of this project is to allow an interested person to run the command ~docker compose up -d~ from a clone of this repo and have phaidra running on his/her computer, without modifying the computer (and have things easily removed with ~docker compose down~ as well).
* Docker notes
  We run the docker services in rootless mode, to avoid uneccesary privileges for the services themselves.  On the downside this means that the reverse-proxy webserver-configuration has to be done on the host's admin level, as unpriviledged docker will not open priviledged ports like 80 and 443.  From a formerly priviledged docker one can do the following to change this:
  #+begin_example
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ docker --version
    Docker version 23.0.4, build f480fb1
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ dockerd-rootless-setuptool.sh install
    [ERROR] Aborting because rootful Docker (/var/run/docker.sock) is running and accessible. Set --force to ignore.
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ sudo systemctl disable --now docker.service docker.socket
    [sudo] password for daniel: 
    Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
    Executing: /lib/systemd/systemd-sysv-install disable docker
    Removed /etc/systemd/system/multi-user.target.wants/docker.service.
    Removed /etc/systemd/system/sockets.target.wants/docker.socket.
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ sudo reboot
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ dockerd-rootless-setuptool.sh install
    [INFO] Creating /home/daniel/.config/systemd/user/docker.service
    [INFO] starting systemd service docker.service
    + systemctl --user start docker.service
    + sleep 3
    + systemctl --user --no-pager --full status docker.service
    ● docker.service - Docker Application Container Engine (Rootless)
         Loaded: loaded (/home/daniel/.config/systemd/user/docker.service; disabled; vendor preset: enabled)
         Active: active (running) since Fri 2023-04-28 09:13:53 CEST; 3s ago
           Docs: https://docs.docker.com/go/rootless/
       Main PID: 4572 (rootlesskit)
          Tasks: 47
         Memory: 146.8M
            CPU: 244ms
         CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/docker.service
                 ├─4572 rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh
                 ├─4583 /proc/self/exe --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh
                 ├─4604 slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 4583 tap0
                 ├─4611 dockerd
                 └─4635 containerd --config /run/user/1000/docker/containerd/containerd.toml --log-level info

    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318881682+02:00" level=warning msg="WARNING: No io.max (wbps) support"
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318884510+02:00" level=warning msg="WARNING: No io.max (riops) support"
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318887369+02:00" level=warning msg="WARNING: No io.max (wiops) support"
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318890069+02:00" level=warning msg="WARNING: bridge-nf-call-iptables is disabled"
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318892767+02:00" level=warning msg="WARNING: bridge-nf-call-ip6tables is disabled"
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318904479+02:00" level=info msg="Docker daemon" commit=cbce331 graphdriver=vfs version=23.0.4
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.318974136+02:00" level=info msg="Daemon has completed initialization"
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.332416560+02:00" level=info msg="[core] [Server #10] Server created" module=grpc
    Apr 28 09:13:53 pcherzigd64 systemd[1834]: Started Docker Application Container Engine (Rootless).
    Apr 28 09:13:53 pcherzigd64 dockerd-rootless.sh[4611]: time="2023-04-28T09:13:53.337229354+02:00" level=info msg="API listen on /run/user/1000/docker.sock"
    + DOCKER_HOST=unix:///run/user/1000/docker.sock /usr/bin/docker version
    Client: Docker Engine - Community
     Version:           23.0.4
     API version:       1.42
     Go version:        go1.19.8
     Git commit:        f480fb1
     Built:             Fri Apr 14 10:32:17 2023
     OS/Arch:           linux/amd64
     Context:           default

    Server: Docker Engine - Community
     Engine:
      Version:          23.0.4
      API version:      1.42 (minimum version 1.12)
      Go version:       go1.19.8
      Git commit:       cbce331
      Built:            Fri Apr 14 10:32:17 2023
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          1.6.20
      GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
     runc:
      Version:          1.1.5
      GitCommit:        v1.1.5-0-gf19387a
     docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0
     rootlesskit:
      Version:          1.1.0
      ApiVersion:       1.1.1
      NetworkDriver:    slirp4netns
      PortDriver:       builtin
      StateDir:         /tmp/rootlesskit2619484379
     slirp4netns:
      Version:          1.0.1
      GitCommit:        6a7b16babc95b6a3056b33fb45b74a6f62262dd4
    + systemctl --user enable docker.service
    Created symlink /home/daniel/.config/systemd/user/default.target.wants/docker.service → /home/daniel/.config/systemd/user/docker.service.
    [INFO] Installed docker.service successfully.
    [INFO] To control docker.service, run: `systemctl --user (start|stop|restart) docker.service`
    [INFO] To run docker.service on system startup, run: `sudo loginctl enable-linger daniel`

    [INFO] Creating CLI context "rootless"
    Successfully created context "rootless"
    [INFO] Using CLI context "rootless"
    Current context is now "rootless"

    [INFO] Make sure the following environment variable(s) are set (or add them to ~/.bashrc):
    export PATH=/usr/bin:$PATH

    [INFO] Some applications may require the following environment variable too:
    export DOCKER_HOST=unix:///run/user/1000/docker.sock

    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ echo $PATH
    /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ sudo loginctl enable-linger daniel
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ cat << 'EOF' >> /home/daniel/.bashrc 
    > export DOCKER_HOST=unix:///run/user/1000/docker.sock
    > EOF
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ source ~/.bashrc
  #+end_example

* Technical sketch
  This is work in progress.
  #+NAME: technical-sketch
  #+begin_src dot :file "./images/construction.svg" :exports results
    graph G {
        graph [rankdir="TB"]
        subgraph cluster_host {
            label = "localhost";
            color = red;
            node [shape = component, style = solid, color = red]
            a1 [label="webserver"];
            a2 [label="developer's browser", shape = doubleoctagon, color = magenta];
            subgraph cluster_host_storage {
                label = "host filesystem";
                node [shape = folder, style = solid, color = blue]
                color = blue;
                b1 [label="Fedora data"];
                b2 [label="MariaDB data"];
                b3 [label="MongoDB data"];
                b4 [label="iipsrv data"];
                b5 [label="Apache Solr data"];
                b6 [label="OpenLDAP data"];
            }
            subgraph cluster_docker_network_host {
                label="PHAIDRA components";
                node [shape = component, style = solid, color = green]
                color = green;
                c1 [label="Fedora\n(object and metadata store)", URL="https://fedora.lyrasis.org/"];
                c2 [label="phaidra-api\n(general transmitter)", URL="https://github.com/phaidra/phaidra-api"];
                c3 [label="MariaDB\n(general databases)", URL="https://mariadb.org/"];
                c4 [label="MongoDB\n(job-tracking)", URL="https://www.mongodb.com/"];
                c5 [label="phaidra-ui\n(webinterface)", URL="https://github.com/phaidra/phaidra-ui"];
                c6 [label="OpenLDAP\n(user management)", URL="https://www.openldap.org/"];
                c7 [label="Apache Solr\n(object search engine)", URL="https://solr.apache.org/"];
                c8 [label="iipsrv\n(display large images)", URL="https://github.com/ruven/iipsrv"];
                c9 [label="pixelgecko\n(image conversion)"]
                c10 [label="dbgate\n(webinterface for databases)"]
                c11 [label="Ldap Account Manager\n(webinterface for openldap)"]
            }}

        d1 [label="Phaidra User", shape = tripleoctagon, style = solid]

            c1 -- c2 [color="green"];
            c2 -- c3 [color="green"];
            c2 -- c4 [color="green"];
            c2 -- c5 [color="green"];
            c2 -- c6 [color="green"];
            c2 -- c7 [color="green"];
            c1 -- c3 [color="green"];
            c2 -- c8 [color="green"];
            c9 -- c8 [color="green"];
            c9 -- c4 [color="green"];
            c10 -- c3 [color="green"];
            c10 -- c4 [color="green"];
            c11 -- c6 [color="green"];

            b1 -- c1 [color="blue"];
            b2 -- c3 [color="blue"];
            b3 -- c4 [color="blue"];
            b4 -- c8 [color="blue"];
            b5 -- c7 [color="blue"];
            b6 -- c6 [color="blue"];

            c2,c5,c10,c11 -- a1 [color="red"];
            c2,c5,c10,c11 -- a2 [color="magenta"];

            a1 -- d1 [color="red"];
    }
  #+end_src

  #+RESULTS: technical-sketch
  [[file:./images/construction.svg]]

* persistance
  To have data persisted, we create at least the following directories:
  #+begin_example
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ mkdir -p ~/phaidra_docker_data/{fedoradb,dbgate,fedora}
  #+end_example
* files
  + [[file:./docker-compose.yml][docker-compose.yml]]
  + [[file:./.env][environment variables for docker-compose.yml]]
* startup services
  #+begin_example
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ mkdir ~/phaidra-docker-data/{dbgate,fedora,fedoradb}
    daniel@pcherzigd64:~/gitlab.phaidra.org/herzigd64/phaidra-docker$ docker compose up -d
  #+end_example
* changes to the phaidra-api repo
  + removed symlinks
  + copied PhaidraAPI.json.example to PhaidraAPI.json
  + run untabify on PhaidraAPI.json
  + run whitespace-cleanup-region on wholly marked buffer
  + removed colon in line 94
  + added colon in line 202
  + copied log4perl.conf from sandbox02
  + changed directory_class from ~Phaidra::Directory::Univie~ to ~Phaidra::Directory::GenericLDAP~.
* changes on the toplevel
  + create [[file:./phaidra.yml][phaidra.yml stub]]
* export this file to markdown
  #+begin_src bash
pandoc README.org --to=gfm -o README.md
  #+end_src

  #+RESULTS:
