* About this repository                                            :noexport:
  We currently have an [[https://gitlab.phaidra.org/phaidra-dev/phaidra-demo][automated installer for phaidra]], which allows to set up an instance in about 15min.  However, setup is still bound to the underlying operating system (Ubuntu 22.04-LTS), which brings quite some complexity to the end-user.  Here we try to abstract the system further and allow for easier integration into CI/CD workflows using containerization via docker, and to achieve better portability to other platforms supporting this kind of containerization.

  The end-goal of this project is to allow an interested person to run the command ~docker compose up~ from a clone of this repo and have phaidra running on his/her computer, without modifying the computer (and have things easily removed with ~docker compose down~ as well).

* Table of Contents                                               :TOC:
- [[#technical-sketch][Technical sketch]]
- [[#changes-to-the-phaidra-api-repo][changes to the phaidra-api repo]]
- [[#changes-on-the-toplevel][changes on the toplevel]]
- [[#add-heading-to-try][add heading to try]]

* Technical sketch
  #+NAME: technical-sketch
  #+begin_src dot :file construction.svg :exports results
    digraph G {
        subgraph cluster0 {
             node [style=filled,color=white];
             style=filled;
             color=lightgrey;
             imageserver -> phaidra_api;
             phaidra_api -> imageserver;
             label = "docker-network";}
    }
  #+end_src

  #+RESULTS: technical-sketch
  [[file:construction.svg]]

* changes to the phaidra-api repo
  + removed symlinks
  + copied PhaidraAPI.json.example to PhaidraAPI.json
  + run untabify on PhaidraAPI.json
  + run whitespace-cleanup-region on wholly marked buffer
  + removed colon in line 94
  + added colon in line 202
  + copied log4perl.conf from sandbox02
  + changed directory_class from ~Phaidra::Directory::Univie~ to ~Phaidra::Directory::GenericLDAP~.
* changes on the toplevel
  + create [[file:./phaidra.yml][phaidra.yml stub]]
* add heading to try
