* About this repository                                            :noexport:
  We currently have an [[https://gitlab.phaidra.org/phaidra-dev/phaidra-demo][automated installer for phaidra]], which allows to set up an instance in about 15min.  However, setup is still bound to the underlying operating system (Ubuntu 22.04-LTS), which brings quite some complexity to the end-user.  Here we try to abstract the system further and allow for easier integration into CI/CD workflows using containerization via docker, and to achieve better portability to other platforms supporting this kind of containerization.

  The end-goal of this project is to allow an interested person to run the command ~docker compose up~ from a clone of this repo and have phaidra running on his/her computer, without modifying the computer (and have things easily removed with ~docker compose down~ as well).

* Table of Contents                                               :TOC:
- [[#technical-sketch][Technical sketch]]
- [[#changes-to-the-phaidra-api-repo][changes to the phaidra-api repo]]
- [[#changes-on-the-toplevel][changes on the toplevel]]

* Technical sketch
  This is work in progress.
  #+NAME: technical-sketch
  #+begin_src dot :file "./images/construction.svg" :exports results
    graph G {
        subgraph cluster_host {
            label = "host";
            color = red;
            subgraph cluster_host_storage {
                label = "host filesystem";
                node [shape = folder, style = solid, color = blue]
                color = blue;
                a1 [label="fedora storage"];
                a2 [label="mariadb storage"];
                a3 [label="mongodb storage"];
                a4 [label="imageserver storage"];
                a5 [label="solr storage"];
                a6 [label="ldap storage"];
            }
            subgraph cluster_docker_network_host {
                label="docker network";
                node [shape = component, style = solid, color = green]
                color = green;
                b1 [label="fedora (data and metadata store)"];
                b2 [label="phaidra-api (general transmitter)"];
                b3 [label="mariadb (general databases)"];
                b4 [label="mongodb (databases for job-tracking)"];
                b5 [label="phaidra-ui (user webinterface)"];
                b6 [label="ldap"];
                b7 [label="solr (site search engine)"];
                b8 [label="imageserver (display large images)"];
                b9 [label="webserver"];
            }}

        subgraph outside_world {
            label="outside world";
            node [shape = tripleoctagon, style = solid]
            c1 [label="Phaidra User"]
            }

            b1 -- b2;
            b2 -- b3;
            b2 -- b4;
            b2 -- b5;
            b2 -- b6;
            b7 -- b5;
            b2 -- b9;
            b5 -- b9;
            b5 -- b1;
            b1 -- b3;
            b2 -- b8;

            a1 -- b1;
            a2 -- b3;
            a3 -- b4;
            a4 -- b8;
            a5 -- b7;
            a6 -- b6;

            c1 -- b9;
    }
  #+end_src

  #+RESULTS: technical-sketch
  [[file:./images/construction.svg]]

* changes to the phaidra-api repo
  + removed symlinks
  + copied PhaidraAPI.json.example to PhaidraAPI.json
  + run untabify on PhaidraAPI.json
  + run whitespace-cleanup-region on wholly marked buffer
  + removed colon in line 94
  + added colon in line 202
  + copied log4perl.conf from sandbox02
  + changed directory_class from ~Phaidra::Directory::Univie~ to ~Phaidra::Directory::GenericLDAP~.
* changes on the toplevel
  + create [[file:./phaidra.yml][phaidra.yml stub]]
