/* eslint-disable */
import './fontello-sort-name-down'
import './fontello-sort-name-up'
import './fontello-sort-number-down'
import './fontello-sort-number-up'
import './material-action-account-balance'
import './material-action-bookmark'
import './material-content-link'
import './material-navigation-close'
import './material-social-person'
import './material-toggle-check-box-outline-blank'
import './orcid'
import './univie-checkbox-unchecked'
import './univie-stop2'
