{
 "title": "Fedora",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "PUT Resource Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"PUT\",uri=\"/rest/{path: .*}\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"fcrepo\",method=\"PUT\"}[1m]) / rate(http_server_requests_seconds_count{job=\"fcrepo\",method=\"PUT\"}[1m])",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "POST Resource Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"POST\",uri=\"/rest/{path: .*}\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"fcrepo\",method=\"POST\"}[1m]) / rate(http_server_requests_seconds_count{job=\"fcrepo\",method=\"POST\"}[1m])",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "GET Resource Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/rest/{path: .*}\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"fcrepo\",method=\"GET\"}[1m]) / rate(http_server_requests_seconds_count{job=\"fcrepo\",method=\"GET\"}[1m])",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=~\".*_ERROR\"}[1m])"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_db_seconds_bucket[1m])) by (le, db, operation))",
     "legendFormat": "{{db}} {{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_db_seconds_sum[1m])/rate(fcrepo_db_seconds_count[1m])",
     "legendFormat": "{{db}} {{operation}} avg"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "OCFL Session Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_storage_ocfl_session_seconds_bucket[1m])) by (le, operation))",
     "legendFormat": "{{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_storage_ocfl_session_seconds_sum[1m])/rate(fcrepo_storage_ocfl_session_seconds_count[1m])",
     "legendFormat": "{{operation}} avg"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{job=\"fcrepo\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "OCFL Object Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_storage_ocfl_object_seconds_bucket[1m])) by (le, operation))",
     "legendFormat": "{{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_storage_ocfl_object_seconds_sum[1m])/rate(fcrepo_storage_ocfl_object_seconds_count[1m])",
     "legendFormat": "{{operation}} avg"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{job=\"fcrepo\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}