{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "docker_services",
    "label": "Docker Services",
    "query": {
     "query": "label_values({container_label_com_docker_compose_service=~\"api|chronos|dbgate|fedora|httpd|imageserver|lam|mariadb-phaidra|mariadb-fedora|openldap|pixelgecko|solr|ui|mongodb-phaidra|promtail-push|vige\"},container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Object Information And Integrity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Repository File Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "fedoradb",
       "rawSql": "SELECT COUNT(fedora_id) FROM fedoradb.simple_search WHERE (fedora_id LIKE '%JSON-LD%' OR fedora_id LIKE '%OCTETS%' OR fedora_id LIKE '%WEBVERSION%' OR fedora_id LIKE '%JSON-LD-PRIVATE%' OR fedora_id LIKE '%UWMETADATA%' OR fedora_id LIKE '%MODS%' OR fedora_id LIKE '%RIGHTS%' OR fedora_id LIKE '%COLLECTIONORDER%' OR fedora_id LIKE '%LINK%' OR fedora_id LIKE '%IIIF-MANIFEST%' OR fedora_id LIKE '%ANNOTATIONS%') LIMIT 50 "
      }
     ]
    },
    {
     "title": "Files By MIME-Type",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "fedoradb",
       "rawSql": "SELECT mime_type, COUNT(mime_type) FROM fedoradb.simple_search WHERE mime_type IS NOT NULL GROUP BY mime_type LIMIT 50 "
      }
     ]
    },
    {
     "title": "Total files checked",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "phaidradb",
       "rawSql": "SELECT COUNT(fedora_id) FROM phaidradb.fixity_states LIMIT 50 "
      }
     ]
    },
    {
     "title": "Oldest Check",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "dataset": "phaidradb",
       "rawSql": "SELECT MIN(last_check) FROM phaidradb.fixity_states LIMIT 50 "
      }
     ]
    },
    {
     "title": "Failed File Check Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "phaidradb",
       "rawSql": "SELECT COUNT(fedora_fixity) FROM phaidradb.fixity_states WHERE fedora_fixity = 'BAD_CHECKSUM' LIMIT 50 "
      }
     ]
    },
    {
     "title": "Failed Files",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "dataset": "phaidradb",
       "rawSql": "SELECT fedora_id, ocfl_topdir FROM phaidradb.fixity_states WHERE fedora_fixity = 'BAD_CHECKSUM' LIMIT 50 "
      }
     ]
    }
   ]
  },
  {
   "title": "Host Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Host Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Host Load 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Container Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_compose_service) (container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$docker_services\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Container CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_compose_service) (rate(container_cpu_system_seconds_total{container_label_com_docker_compose_service=~\"$docker_services\"}[10m]))",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "Container received bytes (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_compose_service) (rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=~\"$docker_services\"}[1m]))",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "Container transmitted bytes (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_compose_service) (rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=~\"$docker_services\"}[1m]))",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "api",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"api\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "cadvisor",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"cadvisor\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "chronos",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"chronos\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "dbgate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"dbgate\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "fedora",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"fedora\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "grafana",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"grafana\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "httpd",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"httpd\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "imageserver",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"imageserver\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "lam",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"lam\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "loki",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"loki\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "vige",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"vige\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "mariadb-fedora",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"mariadb-fedora\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "mariadb-phaidra",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"mariadb-phaidra\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "mongodb-phaidra",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"mongodb-phaidra\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "node-exporter",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"node-exporter\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "openldap",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"openldap\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "pixelgecko",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"pixelgecko\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "prometheus",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"prometheus\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "promtail-local",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"promtail-local\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "solr",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"solr\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "ui",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"ui\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    },
    {
     "title": "promtail-push",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_last_seen{container_label_com_docker_compose_service=\"promtail-push\"}",
       "legendFormat": "{{container_label_com_docker_compose_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "STDOUT",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "{job=\"containerlogs\", logstream=\"stdout\"} != `\"ctx\":` != `/grafana/api` != `\"GET /lam/ HTTP/1.1\" 200 624 \"-\" \"Wget/1.21\"` != `GET /grafana`"
      }
     ]
    },
    {
     "title": "STDERR",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "{job=\"containerlogs\", logstream=\"stderr\"} !~ `caller=[a-z_]*.go`"
      }
     ]
    }
   ]
  }
 ]
}