declare -p | grep -E '|MARIADB_PHAIDRA_USER|MARIADB_PHAIDRA_PASSWORD|MARIADB_PHAIDRA_HOST|FEDORA_OCFL_ROOT|IMAGESERVER_ROOT_PATH|MONGODB_HOST|MONGODB_PHAIDRA_USER|MONGODB_PHAIDRA_PASSWORD' > /container.env
crontab /mnt/api/api-crontab.txt
service cron start
tail -F anything