{
 "title": "Phaidra Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "api, ui & cron",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "api logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{phaidra_app=\"api\"} |= ``"
      }
     ]
    },
    {
     "title": "ui logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "{container=\"ui\"} |= ``"
      }
     ]
    },
    {
     "title": "chronos logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{container=\"chronos\", phaidra_app=\"chronos\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "object repository",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "fedora logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{container=\"fedora\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "search engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "solr logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{container=\"solr\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "mongodb-phaidra logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{container=\"mongodb-phaidra\"} |= ``"
      }
     ]
    },
    {
     "title": "mariadb-fedora logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "{container=\"mariadb-fedora\"} |= ``"
      }
     ]
    },
    {
     "title": "mariadb-phaidra logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{container=\"mariadb-phaidra\"} |= ``"
      }
     ]
    },
    {
     "title": "dbgate logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "{container=\"dbgate\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "image engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "pixelgecko logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "{container=\"pixelgecko\"} |= ``"
      }
     ]
    },
    {
     "title": "imageserver logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "{container=\"imageserver\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "user management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "openldap logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{container=\"openldap\"} |= ``"
      }
     ]
    },
    {
     "title": "lam logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "{container=\"lam\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "webserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "httpd logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{container=\"httpd\", phaidra_app=\"httpd\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}