declare -p | grep -E 'MARIADB_ROOT_PASSWORD|PHAIDRADB|FEDORADB|MONGODB_PHAIDRA_USER|MONGODB_PHAIDRA_PASSWORD|PHAIDRA_HOSTNAME|PHAIDRA_PORTSTUB|PHAIDRA_HOSTPORT|OUTSIDE_HTTP_SCHEME|PHAIDRA_ADMIN_USER|PHAIDRA_ADMIN_PASSWORD|FEDORA_ADMIN_USER|FEDORA_ADMIN_PASS|SOLR_HOST|MARIADB_FEDORA_HOST|MARIADB_PHAIDRA_HOST|MONGODB_PHAIDRA_HOST|FEDORA_HOST' > /container.env
crontab /mnt/chronos/chronos-crontab.txt
service cron start
tail -F anything
