apiVersion: 1

providers:
  - name: Default
    folder: Presets
    folderUid: presets
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /mnt/grafana/dashboards
